# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Class-DBI-Pager
version:      0.07
version_from: lib/Class/DBI/Pager.pm
installdirs:  site
requires:
    Class::DBI:                    0.9
    Data::Page:                    0.13
    Exporter::Lite:                0.01
    Test::More:                    0.32

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.27
